D vf toggle dejudder;vf toggle fps=30000/1001;vf toggle fieldmatch=cthresh=12;vf toggle bwdif=mode=0:deint=interlaced;vf toggle decimate
g change-list glsl-shaders toggle "~~/shaders/ArtCNN_C4F32.glsl"
h cycle auto-window-resize
k vf toggle zscale=in_range=limited:out_range=full:dither=ordered;vf toggle setrange=limited