D vf toggle "dejudder,fps=30000/1001,fieldmatch=cthresh=10,bwdif=mode=send_frame:deint=interlaced,decimate"
g change-list glsl-shaders toggle "~~/shaders/ArtCNN_C4F32.glsl"
h cycle auto-window-resize
k vf toggle "zscale=out_range=full:dither=random,setrange=limited"
