profile=high-quality
profile=osd-box

target-contrast=inf
blend-subtitles=yes

screenshot-format=png
screenshot-dir="~~/screenshots"
screenshot-template="%f %P %02n"

title=${filename} - ${mpv-version}
image-display-duration=inf
taskbar-progress=no
keep-open=always
autofit=75%x75%
volume-max=100
pause=yes

autocreate-playlist=same
directory-mode=ignore
audio-file-auto=fuzzy
sub-auto=fuzzy

osd-font="Cascadia Code"
osd-font-size=15
osd-bar=no

[auto-blend-subtitles]
profile-cond=get("current-tracks/sub/codec"):match("subrip")
profile-restore=copy
blend-subtitles=no

[auto-loop]
profile-cond=p.duration > 0 and p.duration <= 30
profile-restore=copy
loop-file=inf

[crunchyroll-layoutres-fix]
profile-cond=p.filename:match("%[SubsPlease%]")
profile-restore=copy
sub-ass-use-video-data=aspect-ratio

[simulcast]
profile-cond=(function(a)for b,c in ipairs(a)do if p.filename:match(c)then return true end end end)({"%[SubsPlease%]","%[Erai%-raws%]","%-VARYG","%[SubsPlus%+%]","%[Yameii%]"})
profile-restore=copy
deband=yes